---
services:
  web:
    build: .
    init: true
    ports:
    - 127.0.0.1:8000:8000
    command: ["daemon"]
    environment:
    - DATABASE_URL=postgres://postgres:postgres@db/what-the-src
    depends_on:
      - db

  worker:
    build: .
    init: true
    command: ["worker"]
    environment:
    - DATABASE_URL=postgres://postgres:postgres@db/what-the-src
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
    - 127.0.0.1:5432:5432
    environment:
    - POSTGRES_DB=what-the-src
    - POSTGRES_PASSWORD=postgres
