use crate::errors::*;
use crate::sbom::Package;
use data_encoding::BASE64;
use std::collections::VecDeque;

pub const STRAIN: &str = "yarn-lock";
pub const VENDOR: &str = "registry.yarnpkg.com";

#[derive(Debug, PartialEq)]
pub struct YarnLock {
    pub data: String,
}

impl YarnLock {
    pub fn parse(&self) -> Result<ParsedLock> {
        let yarn = yarn_lock_parser::parse_str(&self.data)?;
        let mut packages = VecDeque::new();
        for entry in yarn.entries {
            let official_registry = entry.resolved.starts_with("https://registry.yarnpkg.com/");

            let checksum = if let Some((family, value)) = entry.integrity.split_once('-') {
                let digest = hex::encode(BASE64.decode(value.as_bytes())?);
                Some(format!("{family}:{digest}"))
            } else {
                None
            };

            // TODO: use entry.resolved as url

            packages.push_back(Package {
                name: entry.name.to_string(),
                version: entry.version.to_string(),
                checksum,
                official_registry,
            });
        }
        Ok(ParsedLock { packages })
    }
}

#[derive(Debug, PartialEq)]
pub struct ParsedLock {
    packages: VecDeque<Package>,
}

impl Iterator for ParsedLock {
    type Item = Package;

    fn next(&mut self) -> Option<Self::Item> {
        self.packages.pop_front()
    }
}

#[cfg(test)]
mod tests {
    use crate::sbom::{Package, Sbom};

    #[test]
    fn test_parse_yarn_lock() {
        let data = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"7zip-bin@~5.1.1":
  version "5.1.1"
  resolved "https://registry.yarnpkg.com/7zip-bin/-/7zip-bin-5.1.1.tgz#9274ec7460652f9c632c59addf24efb1684ef876"
  integrity sha512-sAP4LldeWNz0lNzmTird3uWfFDWWTeg6V/MsmyyLR9X1idwKBWIgt/ZvinqQldJm3LecKEs1emkbquO6PCiLVQ==

"@aashutoshrathi/word-wrap@^1.2.3":
  version "1.2.6"
  resolved "https://registry.yarnpkg.com/@aashutoshrathi/word-wrap/-/word-wrap-1.2.6.tgz#bd9154aec9983f77b3a034ecaa015c2e4201f6cf"
  integrity sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==

"@adobe/css-tools@^4.3.0":
  version "4.3.2"
  resolved "https://registry.yarnpkg.com/@adobe/css-tools/-/css-tools-4.3.2.tgz#a6abc715fb6884851fca9dad37fc34739a04fd11"
  integrity sha512-DA5a1C0gD/pLOvhv33YMrbf2FK3oUzwNl9oOJqE4XVjuEtt6XIakRcsd7eLiOSPkp1kTRQGICTA8cKra/vFbjw==

"@protobufjs/fetch@^1.1.0":
  version "1.1.0"
  resolved "https://registry.yarnpkg.com/@protobufjs/fetch/-/fetch-1.1.0.tgz#ba99fb598614af65700c1619ff06d454b0d84c45"
  dependencies:
    "@protobufjs/aspromise" "^1.1.1"
    "@protobufjs/inquire" "^1.1.0"

"@protobufjs/float@^1.0.2":
  version "1.0.2"
  resolved "https://registry.yarnpkg.com/@protobufjs/float/-/float-1.0.2.tgz#5e9e1abdcb73fc0a7cb8b291df78c8cbd97b87d1"

"@types/json5@^0.0.29":
  version "0.0.29"
  resolved "https://registry.yarnpkg.com/@types/json5/-/json5-0.0.29.tgz#ee28707ae94e11d2b827bcbe5270bcea7f3e71ee"
  integrity sha1-7ihweulOEdK4J7y+UnC86n8+ce4=

write-file-atomic@^5.0.0:
  version "5.0.0"
  resolved "https://registry.yarnpkg.com/write-file-atomic/-/write-file-atomic-5.0.0.tgz#54303f117e109bf3d540261125c8ea5a7320fab0"
  integrity sha512-R7NYMnHSlV42K54lwY9lvW6MnSm1HSJqZL3xiSgi9E7//FYaI74r2G0rd+/X6VAMkHEdzxQaU5HUOXWUz5kA/w==
  dependencies:
    imurmurhash "^0.1.4"
    signal-exit "^3.0.7"
"#;
        let yarn = Sbom::new("yarn-lock", data.to_string()).unwrap();
        let list = yarn.to_packages().unwrap();
        assert_eq!(
            list,
            [
                Package {
                    name: "7zip-bin".to_string(),
                    version: "5.1.1".to_string(),
                    checksum: Some("sha512:b003f82e575e58dcf494dce64e2adddee59f1435964de83a57f32c9b2c8b47d5f589dc0a056220b7f66f8a7a9095d266dcb79c284b357a691baae3ba3c288b55" .to_string()),
                    official_registry: true,
                },
                Package {
                    name: "@aashutoshrathi/word-wrap".to_string(),
                    version: "1.2.6".to_string(),
                    checksum: Some("sha512:d588ecd92bccf137e5111fce0f770e8e15963996f9f00dadef0a44d92f577c161388897e5c58501b66e3cb83eed48f8402508d533443603745c056142af5dc20".to_string()),
                    official_registry: true,
                },
                Package {
                    name: "@adobe/css-tools".to_string(),
                    version: "4.3.2".to_string(),
                    checksum: Some("sha512:0c0e5ad42d200ffa4b3af86fdf760cadb7f614ade8533c0d97da0e26a1385d58ee12db7a5c86a445cb1dede2e23923e4a7591345018809303c70aadafef15b8f".to_string()),
                    official_registry: true,
                },
                Package {
                    name: "@protobufjs/fetch".to_string(),
                    version: "1.1.0".to_string(),
                    checksum: None,
                    official_registry: true,
                },
                Package {
                    name: "@protobufjs/float".to_string(),
                    version: "1.0.2".to_string(),
                    checksum: None,
                    official_registry: true,
                },
                Package {
                    name: "@types/json5".to_string(),
                    version: "0.0.29".to_string(),
                    checksum: Some("sha1:ee28707ae94e11d2b827bcbe5270bcea7f3e71ee".to_string()),
                    official_registry: true,
                },
                Package {
                    name: "write-file-atomic".to_string(),
                    version: "5.0.0".to_string(),
                    checksum: Some("sha512:47b3583271d2955e362b9e25c18f65bd6e8c9d29b51d226a64bdf1892822f44efffc561a23be2bd86d2b77efd7e9500c90711dcf141a5391d4397594cf9900ff" .to_string()),
                    official_registry: true,
                },
            ]
        );
    }
}
