name: Docker

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3

    - name: Expose actions cache variables
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        tags: whatsrc
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          UPDATE_CHECK_COMMIT=${{ github.sha }}

    - name: Test the Docker image
      run: |
        docker run --rm whatsrc --help

    - name: Login to github container registry
      if: github.event_name != 'pull_request' && ( github.ref_name == 'main' || github.ref_type == 'tag' )
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the image to `edge`
      if: github.event_name == 'push' && github.ref_name == 'main'
      run: |
        docker tag whatsrc ghcr.io/${{ github.repository }}:edge
        docker push ghcr.io/${{ github.repository }}:edge

    - name: Push the image to `${{ github.ref_name }}`
      if: github.ref_type == 'tag'
      run: |
        docker tag whatsrc ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}

    - name: Push the image to `latest`
      if: github.ref_type == 'tag'
      run: |
        docker tag whatsrc ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:latest
